#!/bin/bash

##########################################
# Partie intégration (Jean François Mai)
##########################################
wget http://eole.ac-dijon.fr/pub/Contribs/Clients_Linux/debian_gnu_linux_jessie_in_scribe2.4-v1.0c.tar.gz
tar xzvf debian_gnu_linux_jessie_in_scribe2.4-v1.0c.tar.gz -C /root

# ip du scribe a modifier dans le fichier /root/jessie/constantes.sh en utilisant la commande 'sed'
sed -i 's/^10.149.46.65/192.168.2.183/' /root/jessie/constantes.sh
#(val 192.168.2.183 correspond a valeur du scribe dans la ligne ci-dessous)


###########################################
# Partie customisation (Simon.B)
###########################################

# Dépot & Mise a jour
wget {{lien a mettre ici sources.list}}
mv -f sources.list /etc/apt/
apt-get update 
apt-get -y install pkg-mozilla-archive-keyring deb-multimedia-keyring
apt-get update
apt-get -y dist-upgrade

# Activation du multiarch 32b 
dpkg --add-architecture i386
apt-get update

# Backportage de Iceweasel alias Firefox 
apt-get -t jessie-backports install iceweasel iceweasel-l10n-fr

# Backportage de LibreOffice
#apt-get -t jessie-backports install libreoffice libreoffice-gtk libreoffice-l10n-fr libreoffice-help-fr
